/*
 * Copyright (c) 2022 Huawei Technologies Co.,Ltd.
 *
 * DMS is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *
 *          http://license.coscl.org.cn/MulanPSL2
 *
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 * -------------------------------------------------------------------------
 *
 * dms_reform_proc_stat.h
 *
 *
 * IDENTIFICATION
 *    src/rc/dms_reform_proc_stat.h
 *
 * -------------------------------------------------------------------------
 */

#ifndef __DMS_REFORM_PROC_STAT_H__
#define __DMS_REFORM_PROC_STAT_H__

#include "dms_reform.h"
#include "dms_reform_proc.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum en_dms_reform_proc_stat {
    DRPS_BASE = DMS_REFORM_STEP_COUNT - 1,
    DRPS_DISCONNECT_GET_LOCK,
    DRPS_DRC_CLEAN_TIMEOUT,
    DRPS_DRC_CLEAN_PAGE,
    DRPS_DRC_CLEAN_PAGE_NO_OWNER = DRPS_DRC_CLEAN_PAGE + DRPS_DRC_CLEAN_NO_OWNER,
    DRPS_DRC_CLEAN_PAGE_NO_CVT = DRPS_DRC_CLEAN_PAGE + DRPS_DRC_CLEAN_NO_CVT,
    DRPS_DRC_CLEAN_PAGE_CONFIRM_COPY = DRPS_DRC_CLEAN_PAGE + DRPS_DRC_CLEAN_CONFIRM_COPY,
    DRPS_DRC_CLEAN_PAGE_OWNER_CVT_FAULT = DRPS_DRC_CLEAN_PAGE + DRPS_DRC_CLEAN_OWNER_CVT_FAULT,
    DRPS_DRC_CLEAN_PAGE_CONFIRM_OWNER = DRPS_DRC_CLEAN_PAGE + DRPS_DRC_CLEAN_CONFIRM_OWNER,
    DRPS_DRC_CLEAN_PAGE_CONFIRM_CVT = DRPS_DRC_CLEAN_PAGE + DRPS_DRC_CLEAN_CONFIRM_CVT,
    DRPS_DRC_CLEAN_LOCK,
    DRPS_DRC_CLEAN_LOCK_NO_OWNER = DRPS_DRC_CLEAN_LOCK + DRPS_DRC_CLEAN_NO_OWNER,
    DRPS_DRC_CLEAN_LOCK_NO_CVT = DRPS_DRC_CLEAN_LOCK + DRPS_DRC_CLEAN_NO_CVT,
    DRPS_DRC_CLEAN_LOCK_CONFIRM_COPY = DRPS_DRC_CLEAN_LOCK + DRPS_DRC_CLEAN_CONFIRM_COPY,
    DRPS_DRC_CLEAN_LOCK_OWNER_CVT_FAULT = DRPS_DRC_CLEAN_LOCK + DRPS_DRC_CLEAN_OWNER_CVT_FAULT,
    DRPS_DRC_CLEAN_LOCK_CONFIRM_OWNER = DRPS_DRC_CLEAN_LOCK + DRPS_DRC_CLEAN_CONFIRM_OWNER,
    DRPS_DRC_CLEAN_LOCK_CONFIRM_CVT = DRPS_DRC_CLEAN_LOCK + DRPS_DRC_CLEAN_CONFIRM_CVT,
    DRPS_DRC_CLEAN_XA,
    DRPS_DRC_REBUILD_PAGE,
    DRPS_DRC_REBUILD_PAGE_LOCAL,
    DRPS_DRC_REBUILD_PAGE_REMOTE,
    DRPS_DRC_REBUILD_PAGE_REMOTE_REST,
    DRPS_DRC_REBUILD_LOCK,
    DRPS_DRC_REBUILD_LOCK_RES,
    DRPS_DRC_REBUILD_LOCK_LOCAL,
    DRPS_DRC_REBUILD_LOCK_REMOTE,
    DRPS_DRC_REBUILD_LOCK_REMOTE_REST,
    DRPS_DRC_REBUILD_TABLE_LOCK,
    DRPS_DRC_REBUILD_TLOCK_LOCAL,
    DRPS_DRC_REBUILD_TLOCK_REMOTE,
    DRPS_DRC_REBUILD_XA,
    DRPS_DRC_REBUILD_XA_LOCAL,
    DRPS_DRC_REBUILD_XA_REMOTE,
    DRPS_DRC_REBUILD_XA_REMOTE_REST,
    DRPS_DRC_MIGRATE_PAGE,
    DRPS_DRC_MIGRATE_LOCK,
    DRPS_DRC_MIGRATE_XA,
    DRPS_DRC_REPAIR_TIMEOUT,
    DRPS_DRC_REPAIR_PAGE,
    DRPS_DRC_REPAIR_PAGE_NEED_FLUSH = DRPS_DRC_REPAIR_PAGE + DRPS_DRC_REPAIR_NEED_FLUSH,
    DRPS_DRC_REPAIR_PAGE_NEED_NOT_FLUSH = DRPS_DRC_REPAIR_PAGE + DRPS_DRC_REPAIR_NEED_NOT_FLUSH,
    DRPS_DRC_REPAIR_PAGE_WITH_COPY = DRPS_DRC_REPAIR_PAGE + DRPS_DRC_REPAIR_WITH_COPY,
    DRPS_DRC_REPAIR_PAGE_WITH_COPY_NEED_FLUSH = DRPS_DRC_REPAIR_PAGE + DRPS_DRC_REPAIR_WITH_COPY_NEED_FLUSH,
    DRPS_DRC_REPAIR_PAGE_WITH_LAST_EDP = DRPS_DRC_REPAIR_PAGE + DRPS_DRC_REPAIR_WITH_LAST_EDP,
    DRPS_DRC_REPAIR_PAGE_WITH_EDP_MAP = DRPS_DRC_REPAIR_PAGE + DRPS_DRC_REPAIR_WITH_EDP_MAP,
    DRPS_DRC_REPAIR_PAGE_WITH_EDP_MAP_GET_LSN = DRPS_DRC_REPAIR_PAGE + DRPS_DRC_REPAIR_WITH_EDP_MAP_GET_LSN,
    DRPS_DRC_REPAIR_LOCK,
    DRPS_DRC_REPAIR_LOCK_NEED_FLUSH = DRPS_DRC_REPAIR_LOCK + DRPS_DRC_REPAIR_NEED_FLUSH,
    DRPS_DRC_REPAIR_LOCK_NEED_NOT_FLUSH = DRPS_DRC_REPAIR_LOCK + DRPS_DRC_REPAIR_NEED_NOT_FLUSH,
    DRPS_DRC_REPAIR_LOCK_WITH_COPY = DRPS_DRC_REPAIR_LOCK + DRPS_DRC_REPAIR_WITH_COPY,
    DRPS_DRC_REPAIR_LOCK_WITH_COPY_NEED_FLUSH = DRPS_DRC_REPAIR_LOCK + DRPS_DRC_REPAIR_WITH_COPY_NEED_FLUSH,
    DRPS_DRC_REPAIR_LOCK_WITH_LAST_EDP = DRPS_DRC_REPAIR_LOCK + DRPS_DRC_REPAIR_WITH_LAST_EDP,
    DRPS_DRC_REPAIR_LOCK_WITH_EDP_MAP = DRPS_DRC_REPAIR_LOCK + DRPS_DRC_REPAIR_WITH_EDP_MAP,
    DRPS_DRC_REPAIR_LOCK_WITH_EDP_MAP_GET_LSN = DRPS_DRC_REPAIR_LOCK + DRPS_DRC_REPAIR_WITH_EDP_MAP_GET_LSN,
    DRPS_DRC_FLUSH_COPY_TIMEOUT,
    DRPS_DRC_FLUSH_COPY_LOCAL,
    DRPS_DRC_FLUSH_COPY_REMOTE,
    DRPS_DRC_EDP_TO_OWNER_LOCAL,
    DRPS_DRC_EDP_TO_OWNER_REMOTE,
    DRPS_DRC_FLUSH_COPY_VALIDATE_LSN,
    DRPS_TXN_DEPOSIT_DELETE_XA,
    DRPS_ROLLBACK_UNDO_INIT,
    DRPS_ROLLBACK_TX_AREA_INIT,
    DRPS_ROLLBACK_TX_AREA_LOAD,
    DRPS_ROLLBACK_CVT_TO_RW,
    DRPS_DRC_BLOCK,
    DRPS_REFORM,
    DRPS_CALLBACK_STAT_CKPT_LATCH,
    DRPS_CALLBACK_STAT_BUCKET_LOCK,
    DRPS_CALLBACK_STAT_SS_READ_LOCK,
    DRPS_CALLBACK_STAT_TLOCK_REMOTE,
    DRPS_CALLBACK_STAT_GET_DISK_LSN,
    DRPS_CALLBACK_STAT_DRC_EXIST,
    DRPS_CALLBACK_STAT_CLEAN_EDP,
    DRPS_CALLBACK_STAT_NEED_NOT_REBUILD,
    DRPS_CALLBACK_STAT_EXPIRE,
    DRPS_MES_TASK_STAT_CONFIRM_OWNER_PAGE,
    DRPS_CALLBACK_MES_TASK_STAT_CONFIRM_OWNER_BUCKET_LOCK,
    DRPS_CALLBACK_MES_TASK_STAT_CONFIRM_OWNER_GET_DISK_LSN,
    DRPS_MES_TASK_STAT_CONFIRM_OWNER_LOCK,
    DRPS_MES_TASK_STAT_CONFIRM_CVT_PAGE,
    DRPS_CALLBACK_MES_TASK_STAT_CONFIRM_CVT_BUCKET_LOCK,
    DRPS_CALLBACK_MES_TASK_STAT_CONFIRM_CVT_SS_READ_LOCK,
    DRPS_MES_TASK_STAT_CONFIRM_CVT_LOCK,
    DRPS_MES_TASK_STAT_NEED_FLUSH,
    DRPS_CALLBACK_MES_TASK_STAT_NEED_FLUSH_ALLOC_CTRL,
    DRPS_CALLBACK_MES_TASK_STAT_NEED_FLUSH_SS_READ_LOCK,
    DRPS_MES_TASK_STAT_EDP_TO_OWNER,
    DRPS_CALLBACK_MES_TASK_STAT_EDP_TO_OWNER_GET_DISK_LSN,
    DRPS_CALLBACK_MES_TASK_STAT_EDP_TO_OWNER_ALLOC_CTRL,
    DRPS_VALIDATE_LOCK_MODE_PAGE,
    DRPS_CALLBACK_STAT_VALIDATE_DRC_PAGE_BUCKET_LOCK,
    DRPS_CALLBACK_STAT_VALIDATE_DRC_PAGE_SS_READ_LOCK,
    DRPS_VALIDATE_LOCK_MODE_PAGE_LOCAL,
    DRPS_VALIDATE_LOCK_MODE_PAGE_REMOTE,
    DRPS_VALIDATE_LOCK_MODE_LOCK,
    DRPS_VALIDATE_LOCK_MODE_LOCK_BUCKET_LOCK,
    DRPS_VALIDATE_LOCK_MODE_LOCK_LOCAL_RES_LOCK,
    DRPS_VALIDATE_LOCK_MODE_LOCK_LOCAL,
    DRPS_VALIDATE_LOCK_MODE_LOCK_REMOTE,
    DRPS_VALIDATE_LOCK_MODE_TLOCK,
    DRPS_VALIDATE_LOCK_MODE_TLOCK_LOCAL,
    DRPS_VALIDATE_LOCK_MODE_TLOCK_REMOTE,
    DRPS_CALLBACK_STAT_VALIDATE_DRC_TLOCK_REMOTE,
    DRPS_MES_TASK_STAT_VALIDATE_LSN,
    DRPS_CALLBACK_MES_TASK_STAT_VALIDATE_LSN_GET_CTRL,
    DRPS_CALLBACK_MES_TASK_STAT_VALIDATE_LSN_GET_CTRL_TIMEOUT,
    DRPS_CALLBACK_MES_TASK_STAT_VALIDATE_LSN_GET_DISK_LSN,
    DRPS_CALLBACK_MES_TASK_STAT_VALIDATE_LSN_BUF_UNLATCH,
    DRPS_VALIDATE_LSN_COUNT,

    /* add new item above */
    DRPS_COUNT
} dms_reform_proc_stat_e;

typedef struct st_dms_reform_proc_stat_item {
    uint64          start_time;
    uint64          total_time;
    uint64          max_time;
    uint64          times;
} drps_item_t;

typedef struct st_dms_reform_proc_stat_items {
    drps_item_t     drps_item[DRPS_COUNT];
} drps_items_t;

typedef struct st_dms_reform_proc_stat {
    drps_items_t    items_total;
    drps_items_t    items_proc_total;
    drps_items_t    items_proc_parallel[DMS_PARALLEL_MAX_THREAD];
    drps_items_t    items_mes_total;
    drps_items_t    items_mes_task[DMS_MAX_WORK_THREAD_CNT];
} drps_t;

typedef struct st_dms_reform_proc_stat_desc {
    uint32          item;
    uint32          level;
    char            desc[CM_BUFLEN_32];
} drps_desc_t;

typedef enum en_drps_level {
    DRPS_LEVEL_TOP = 0,
    DRPS_LEVEL_ONE,
    DRPS_LEVEL_TWO,
    DRPS_LEVEL_THREE,

    DRPS_LEVEL_COUNT
} drps_level_e;

typedef struct st_drps_level_format {
    char        format[CM_BUFLEN_64];
} drps_level_format_t;

void dms_reform_proc_stat_start(uint32 item);
void dms_reform_proc_stat_end(uint32 item);
void dms_reform_proc_stat_times(uint32 item);
void dms_reform_proc_stat_bind_proc(void);
void dms_reform_proc_stat_bind_proc_parallel(uint32 index);
void dms_reform_proc_stat_bind_mes_task(uint32 index);
void dms_reform_proc_stat_clear_total(void);
void dms_reform_proc_stat_clear_current(void);
void dms_reform_proc_stat_collect_total(void);
void dms_reform_proc_stat_collect_current(void);
void dms_reform_proc_stat_log_total(void);
void dms_reform_proc_stat_log_current(void);
bool32 dms_reform_proc_stat_desc_check(void);

#ifdef __cplusplus
}
#endif
#endif